# Generated by Django 6.0 on 2025-12-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviewer_interface", "0002_alter_testtemplate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Свободный текст"),
                    ("single_choice", "Выбор одного варианта"),
                    ("multiple_choice", "Выбор нескольких вариантов"),
                    ("code", "Написать код"),
                ],
                default="text",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Текст варианта"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Правильный вариант"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="interviewer_interface.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
        ),
    ]
