# Generated by Django 6.0 on 2025-12-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer_interface', '0003_question_question_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stdin',
            field=models.TextField(blank=True, verbose_name='Входные данные для кода'),
        ),
    ]
