# Generated by Django 6.0 on 2025-12-26 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviewer_interface', '0002_alter_testtemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email кандидата')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальная ссылка')),
                ('sent', models.BooleanField(default=False, verbose_name='Ссылка отправлена')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='candidate_interface.candidate', verbose_name='Кандидат')),
                ('test_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='interviewer_interface.testtemplate', verbose_name='Шаблон теста')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='Ответ кандидата')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewer_interface.question', verbose_name='Вопрос')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='candidate_interface.invitation', verbose_name='Приглашение')),
            ],
        ),
    ]
