# Generated by Django 6.0 on 2025-12-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы (автооценка)'),
        ),
    ]
