# Generated by Django 6.0 on 2025-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_interface", "0003_invitation_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="tab_switches",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество уходов с вкладки"
            ),
        ),
    ]
