# Generated by Django 6.0 on 2025-12-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_interface', '0004_answer_tab_switches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='tab_switches',
            new_name='switches',
        ),
    ]
