# Generated by Django 6.0 on 2026-01-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_interface", "0007_remove_invitation_last_switch_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "permissions": [
                    ("can_assign_interview", "Can assign technical interview")
                ]
            },
        ),
    ]
