# Generated by Django 6.0 on 2026-01-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_interface', '0008_alter_invitation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'permissions': [('can_assign_interview', 'can_assign_technical_interview')]},
        ),
    ]
