# Generated by Django 6.0 on 2026-01-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_interface", "0009_alter_invitation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "permissions": [
                    ("can_assign_interview", "can assign hr interview"),
                    ("can_assign_tech_interview", "can assign tech interview"),
                ]
            },
        ),
    ]
