# Generated by Django 6.0 on 2026-01-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_interface", "0012_invitation_assigned_tech_lead"),
        (
            "interviewer_interface",
            "0010_intervieweruser_is_hr_intervieweruser_is_tech_lead",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="interview_type",
            field=models.CharField(
                choices=[
                    ("general", "Общий тест (HR)"),
                    ("technical", "Техническое собеседование (Tech Lead)"),
                ],
                default="general",
                max_length=20,
                verbose_name="Тип собеседования",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="tech_comments",
            field=models.TextField(
                blank=True, verbose_name="Итоговый комментарий Tech Lead"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="tech_total_score",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Итоговый балл от Tech Lead"
            ),
        ),
        migrations.CreateModel(
            name="QuestionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий по вопросу"),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Баллы за вопрос"
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="candidate_interface.invitation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interviewer_interface.question",
                    ),
                ),
            ],
            options={
                "unique_together": {("invitation", "question")},
            },
        ),
    ]
