# Generated by Django 6.0 on 2026-01-11 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate_interface",
            "0013_invitation_interview_type_invitation_tech_comments_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        help_text="Общий балл (0-100)",
                        verbose_name="Ручной балл",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий оценивающего"
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(auto_now=True, verbose_name="Время оценки"),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Оценил",
                    ),
                ),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_grade",
                        to="candidate_interface.invitation",
                        verbose_name="Приглашение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ручная оценка",
                "verbose_name_plural": "Ручные оценки",
            },
        ),
    ]
